#!/usr/bin/env bash
# configure web-02 to be identical to web-01
#sudo sed -i 's/server_name _;.*/server_name _;\n\tadd_header X-Served-By \$hostname;/' /etc/nginx/sites-enabled/default 
sudo mkdir -p /var/www/html /var/www/html/error
sudo chmod -R 755 /var/www
echo 'Hello World!' | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error/404.html
server_config=\
"server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    add_header X-Served-By `hostname`;
    location / {
        try_files \$uri \$uri/ =404;
    }
    if (\$request_filename ~ redirect_me){
        rewrite ^ https://youtube.com permanent;
    }
    error_page 404 /error/404.html;
    location = /error/404.html {
        internal;
    }
}"

echo "$server_config" | sudo tee /etc/nginx/sites-available/default
sudo service nginx restart
