#!/usr/bin/env bash
# Configure Nginx
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get -y update

# Install HAProxy
sudo apt-get -y install haproxy
sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy
sudo sed -i -e '$a\listen http-in\n\tbind :80\n\tbalance roundrobin\n\tserver 428861-web-01 100.25.41.77:80 check\n\tserver 428861-web-02 3.86.13.40:80 check\n' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
